### ISSUE TITLE
train_rnn_mask.sh

### ISSUE THREAD

**Issue by YeBobr** [funcwj/setk#18]
Hello, 
  In the "train_rnn_mask.sh", the output layer includes the option "include-activation= ", but I complied it in error. Can you help me? 
  Thank you!

**Comment by funcwj** [comment]
You can check the modification in my branch [https://github.com/funcwj/kaldi/blob/8c1d34e03977c2dcb592139da9692ea92e1c14bf/egs/wsj/s5/steps/libs/nnet3/xconfig/basic_layers.py#L445](https://github.com/funcwj/kaldi/blob/8c1d34e03977c2dcb592139da9692ea92e1c14bf/egs/wsj/s5/steps/libs/nnet3/xconfig/basic_layers.py#L445)
