### ISSUE TITLE
error occurred while compiling setk with kaldi & OpenBLAS

### ISSUE THREAD

**Issue by Fuann** [funcwj/setk#19]
I patched kaldi/src/matrix/matrix-common.h in kaldi and followed the instruction:

mkdir build
cd build
export KALDI_ROOT=/kaldi/root/dir
export OPENBLAS_ROOT=/openblas/root/dir
cmake ..
make -j

then got this error below:

/usr/include/c++/5/bits/basic_string.h:5172:5: note: candidate: template<class _CharT, class _Traits, class _Alloc> std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&)
     operator<<(basic_ostream<_CharT, _Traits>& __os,
     ^
/usr/include/c++/5/bits/basic_string.h:5172:5: note:   template argument deduction/substitution failed:
......./setk/include/beamformer.cc:174:50: note:   'kaldi::MessageLogger' is not derived from 'std::basic_ostream<_CharT, _Traits>'
                   << std::imag(s) << ")" << std::endl;
                                                  ^
include/CMakeFiles/setk.dir/build.make:182: recipe for target 'include/CMakeFiles/setk.dir/beamformer.cc.o' failed
make[2]: *** [include/CMakeFiles/setk.dir/beamformer.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:85: recipe for target 'include/CMakeFiles/setk.dir/all' failed
make[1]: *** [include/CMakeFiles/setk.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Can somebody help,plz ? 
THX.

**Comment by funcwj** [comment]
I fix it now.

**Comment by Fuann** [comment]
> I fix it now.

thanks for the reply,
but I encounter another err:

Scanning dependencies of target setk
[  2%] Building CXX object include/CMakeFiles/setk.dir/complex-vector.cc.o
[ 13%] Building CXX object include/CMakeFiles/setk.dir/complex-matrix.cc.o
[ 13%] Building CXX object include/CMakeFiles/setk.dir/rir-generator.cc.o
[ 11%] Building CXX object include/CMakeFiles/setk.dir/stft.cc.o
[ 13%] Building CXX object include/CMakeFiles/setk.dir/srp-phat.cc.o
[ 13%] Building CXX object include/CMakeFiles/setk.dir/beamformer.cc.o
[ 16%] Linking CXX shared library ../../lib/libsetk.so
/usr/bin/ld: cannot find -lkaldi-base
/usr/bin/ld: cannot find -lkaldi-util
/usr/bin/ld: cannot find -lkaldi-matrix
/usr/bin/ld: cannot find -lkaldi-feat
/usr/bin/ld: cannot find -lkaldi-transform
collect2: error: ld returned 1 exit status
include/CMakeFiles/setk.dir/build.make:224: recipe for target '../lib/libsetk.so' failed
make[2]: *** [../lib/libsetk.so] Error 1
CMakeFiles/Makefile2:85: recipe for target 'include/CMakeFiles/setk.dir/all' failed
make[1]: *** [include/CMakeFiles/setk.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by funcwj** [comment]
Seems your compile of Kaldi do not produces dynamic library in `src/lib`. Use `./configure --shared ...` instead.

**Comment by Fuann** [comment]
> Seems your compile of Kaldi do not produces dynamic library in `src/lib`. Use `./configure --shared ...` instead.

It seems that I forgot to build Kaldi shared libraries.
After that, it successfully compiled !
Thanks for the help !
