### ISSUE TITLE
Size not matched

### ISSUE THREAD

**Issue by hangtingchen** [funcwj/setk#24]
Hi,
Thanks a lot for your code!
In the line
https://github.com/funcwj/setk/blob/master/include/stft.cc#L237
you want to add [0: end - s] and [-s: end], but you write 

> denominator.Range(0, window_size + s).AddVec(1, analysis_window_square.Range(-s, window_size + s));
The size is not matched. Is this a bug?

**Comment by funcwj** [comment]
Hi, have you test it? I remember that the two parameters in the matrix function `Range(...)` means index shift and length so the size is matched.

**Comment by hangtingchen** [comment]
Yes, you're right
thanks a lot!
