### ISSUE TITLE
--src-begin=32000,0 \     --src-sdr=3 \

### ISSUE THREAD

**Issue by fanmanqian** [funcwj/setk#43]
在进行两个.wav文件混合时，如果我是对原始的两个音频混合的话，上面的这两个参数要改成多少？还是就是使用这个原始的就可以？

**Comment by funcwj** [comment]
--src-sdr: 混合的信噪比，一般每个句子不一样，在某个区间内随机采样
--src-begin: 混合位置，默认为0就行
建议：
代码都比较简单，自己看一下参数释义就能理解，sdr这些基本的概念做之前你得自己弄清楚

**Comment by fanmanqian** [comment]
好的，非常感谢~


 
---Original---
