### ISSUE TITLE
online beamforming的speech mask、noise mask怎么得到的

### ISSUE THREAD

**Issue by Ryuk17** [funcwj/setk#46]
你好，我看你代码发现online beamforming初始的mask是从文件读入的，请问有什么计算方法么？此外，看这个更新参数的方法只是简单的通过平滑函数alpha更新的，并不是你这个[repo](https://github.com/funcwj/CGMM-MVDR)的方法对吧。

顺便 def do_online_beamform这个函数中的
`chunk = beamformer.run(speech_mask[base:base + chunk_size],  stft_mat[:, :, base:base + chunk_size], noise_mask=noise_mask,   normalize=ban)`
run函数中没有normalize属性

**Comment by funcwj** [comment]
可以用无监督的空间聚类方法或者神经网络估计，里面写的online beamforming并没用考虑mask的online估计。那个repo里面的实现的也是offline的算法，原始论文的思路除了mask是online估计的之外，相关矩阵上也有类似的平滑操作

**Comment by Ryuk17** [comment]
请问初始值对算法收敛影响大么？

**Comment by funcwj** [comment]
你指的是EM的初始值吗，如果估完mask做一个frequency的permutation调整的算法，我觉得结果差不多，但是如果不做的话，初始值影响收敛方向，结果有影响

**Comment by Ryuk17** [comment]
我指的是online beamforming的空间相关矩阵R的初始值，如果用均匀分布初始化noisy speech，用单位矩阵初始化noise only这样和使用训练数据初始化差异大不大，应为使用场景总是不同的，为每个场景训练一个初始化的矩阵也不现实

**Comment by funcwj** [comment]
理论上用一部分noise only段做初始化是好的（比如句子开头一小部分等等），但是由于BF对mask还是比较鲁棒的，如果mask层面差异不大的话，最终结果可能也没什么区别。所以我一般都用的单位矩阵初始化。

**Comment by Ryuk17** [comment]
也就是说，需要加个类似于唤醒检测的算法，捕获语音开始前的noise当做noise only 的mask

**Comment by funcwj** [comment]
是的，一般可以这么做的
