### ISSUE TITLE
mask.scp file for adaptive beamformer

### ISSUE THREAD

**Issue by rakshithkamath** [funcwj/setk#50]
Hello,
I wanted to understand for the adaptive_beamformer example present in setk/doc/adaptive_beamformer/ how msk.scp is defined so as to run the file. I've tried to run it by creating a mask.scp file which involves the path of the egs.npy mask file which was created from the  previous scripts. Any help would be appreciated.

**Comment by funcwj** [comment]
Hi, I just push a commit to fix this issue. The generation of "mask.scp" is missing in the README.md. Thanks for pointing out this.

The line format of the .scp file in this toolkit is defined as "{unique-key-for-each-utterance} {path-to-the-file}". The unique key is used to index the pair-wise relationship between the objects, e.g., audio and TF mask file.
